[[CFITSIO]]
arch = "aarch64"
git-tree-sha1 = "0d5b5106d527ec0c89551d2e97bc474e3b5ef9aa"
os = "macos"

    [[CFITSIO.download]]
    sha256 = "c78a4af678acfa70c9c155ead01617164cd1d41df1324b075c6d6fae2e10ebb1"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.4.0+0/CFITSIO.v4.4.0.aarch64-apple-darwin.tar.gz"
[[CFITSIO]]
arch = "aarch64"
git-tree-sha1 = "6e200dca68da6bb0afa67741a8522a5b9d3d36a8"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "067dd35e64d51cd68917f50c1d876b2052b51ca037aa7e038758e189194f1827"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.4.0+0/CFITSIO.v4.4.0.aarch64-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "aarch64"
git-tree-sha1 = "ab4d3450c1422212b2726e2e47368ba54b17e822"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "6b01c4c621f34bec1cb6dd780636cb321efea54077a12de27ab3d4294e3b76d7"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.4.0+0/CFITSIO.v4.4.0.aarch64-linux-musl.tar.gz"
[[CFITSIO]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f92194236b66b3408fc869a2756f1763f4f7bf9f"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "5a782a98a4cfcfe9b02858bdc92d54c905fb1cf03b70b04e39739e40e82fe8e3"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.4.0+0/CFITSIO.v4.4.0.armv6l-linux-gnueabihf.tar.gz"
[[CFITSIO]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c15680cc682df46f4efa045904225b3dc73502a2"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "b17f201e9ca20ac1c0d8445c74e6dc82af3635195f7401a44f4de8c2c99cf46f"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.4.0+0/CFITSIO.v4.4.0.armv6l-linux-musleabihf.tar.gz"
[[CFITSIO]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fd73abf75c26fc4460743dfe1553cd3611377d18"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "67942360619f0b7a8db288e80b4583450bc0348c324f6b2d4aa1ba7f81ea46ad"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.4.0+0/CFITSIO.v4.4.0.armv7l-linux-gnueabihf.tar.gz"
[[CFITSIO]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b7e3aa0786c3911dece2099de004f46fc2f06dba"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "300054e6d6c5d2a9d39eebbbfd5c47f0950aa5b88a7c5e21f1b16a0d4d93fb38"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.4.0+0/CFITSIO.v4.4.0.armv7l-linux-musleabihf.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "0d8624a97e2f235fc9f6e6a142ae34a4de6e80a1"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "cb5989b37e281ca9976b2b9112d55f6ee049a7766474942bceed534877175c10"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.4.0+0/CFITSIO.v4.4.0.i686-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "34feb2293b3fdfaa5c726e14a246593fcb9b404a"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "de04d09b757f13325584c386091991eeb93f1bf5be6105234fa4e9807798dddb"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.4.0+0/CFITSIO.v4.4.0.i686-linux-musl.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "c25999feb856e5762149c30e6c1974d189befbb7"
os = "windows"

    [[CFITSIO.download]]
    sha256 = "1f41c4d43356b213221effe3d7c327f2410e74e13947470071050a6e35a514f2"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.4.0+0/CFITSIO.v4.4.0.i686-w64-mingw32.tar.gz"
[[CFITSIO]]
arch = "powerpc64le"
git-tree-sha1 = "47c443b25c7a5d1b61793a9446e888b14d948574"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "3af20a1e895655486e9a5e9801367f5a48dbf4e65a73a07de417f6b310ef34a4"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.4.0+0/CFITSIO.v4.4.0.powerpc64le-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "39dd3478c37fc004ab12c99b61b8c43606856aa9"
os = "macos"

    [[CFITSIO.download]]
    sha256 = "d8cf4bb0f1fe85f190e4a22b826eee33cab8d3a2042ad4607bf88cb64dc91e30"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.4.0+0/CFITSIO.v4.4.0.x86_64-apple-darwin.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "97898729db34fede96e4df9518b11dc73191a174"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "448182bd3e105613f61d823772d4b9272687c773cb7a5a3bad481ced444747e1"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.4.0+0/CFITSIO.v4.4.0.x86_64-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "7d0249d9041e37015966ce42b3f6a54986d08f82"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "93500de36086f997cd7958fc5821a45bf962e638427a8c52125a5b1d0a7054e1"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.4.0+0/CFITSIO.v4.4.0.x86_64-linux-musl.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "869ab010a4bafbda1cb2c05c92b61c0a281d8960"
os = "freebsd"

    [[CFITSIO.download]]
    sha256 = "6a2829eef8572c6e12f4bc2675c0d5be1982433717bd741423be4470f7231b75"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.4.0+0/CFITSIO.v4.4.0.x86_64-unknown-freebsd.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "93145a124641012eac9844c740227cff8f52b04d"
os = "windows"

    [[CFITSIO.download]]
    sha256 = "f53dbed0c4dedf832cc54ef1000df8c2e7dfa5069577283d0dfaa3573e6b5046"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.4.0+0/CFITSIO.v4.4.0.x86_64-w64-mingw32.tar.gz"
