[[CFITSIO]]
arch = "aarch64"
git-tree-sha1 = "2dcc73c355cc7c8619f979f411300f6ab5a82273"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "75269f8b43da2723f5ca67c2f39266e843afd52a3c5a71f073391f12c604b3d9"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.aarch64-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "aarch64"
git-tree-sha1 = "78855897734509a13c3a043eb4c2cb573054d89c"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "82943859c3e1f00f332fbc782e2cbe0be02ed83796a1fa3f823925a65f8b41ce"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.aarch64-linux-musl.tar.gz"
[[CFITSIO]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4ad86e0c7a41a320cecc4a00077b474510130326"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "4c35914ac2968feb64e6716575e97f261ab32b4cad3b897fa8a945d9b908e50a"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.armv7l-linux-gnueabihf.tar.gz"
[[CFITSIO]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d389180a94ce9bbad764e712c42a3199fd5e1d2b"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "da24df2c9f29af155c25eee73b900223a4048bd33224016b849b972bc2f7c257"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.armv7l-linux-musleabihf.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "66074794b5d01aa0a9f975ee533f8ea39c073f51"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "3057a97a31d69314379f30c95e6e4835e0680461098a06d8c4fcdcb4327ae46e"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.i686-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "ad0cd731cfe01268c112a5a359bb791cf71a9a64"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "6fffc092c01372688cac8702aae6a63c61d84c4368e3e31b9a280e3385b57fb7"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.i686-linux-musl.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "e03e9d1715b01dffb386b8defd3f532df3df4944"
os = "windows"

    [[CFITSIO.download]]
    sha256 = "99ba81e18035aacc0ffe40b629262f99c30057a13142d3290550eef310c5f5c3"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.i686-w64-mingw32.tar.gz"
[[CFITSIO]]
arch = "powerpc64le"
git-tree-sha1 = "5168039df5265a0b86c7ae2e9a6e8b990ec1a06e"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "36592a931dd7e7f265d69dcf47b6b138685b20bccb9c0094e9bfe735131c94f9"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.powerpc64le-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "27e2a53efd29ebd5fb5e96fc8bb251d09b510fc1"
os = "macos"

    [[CFITSIO.download]]
    sha256 = "460c2ca6f6d772ca3a6a60fd2395b72e6ff77b056a819329be7bea348f697034"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.x86_64-apple-darwin.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "fa2eaecc0bc0821a87dfeea7e453c22a400177e9"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "ba9f8da823f22c9881821fbc378814ab7cffca6d98d3d754a0636c8588ba30a4"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.x86_64-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "caaeaf4d122ef47d37cc265466aa554423ec692f"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "b0234a320ce7640061220507b997fce8ac03b31453a6c6482b271b0e03b65236"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.x86_64-linux-musl.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "29980c8404451f0d9e4c6edbc5dab42f2e201f71"
os = "freebsd"

    [[CFITSIO.download]]
    sha256 = "6892cadc72ba0755ec4503a4b6caecac4bffac4aeca80fce79c87489fbd5670a"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.x86_64-unknown-freebsd.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "524fd67382b3f601cbecad9582884a3846a89f29"
os = "windows"

    [[CFITSIO.download]]
    sha256 = "505787ae99ec4c1f7563fa2152fcc6c8a3e3e32bf72cbc3d85f13f1a6d6a3929"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.x86_64-w64-mingw32.tar.gz"
