[[CFITSIO]]
arch = "aarch64"
git-tree-sha1 = "fa0b5216e0a4e80fc19190be06e4d59c807f85fc"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "978e316fdb1500862ab3ced3055d31efce620140b01f80a639a9e257f901e97e"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.aarch64-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "aarch64"
git-tree-sha1 = "2dde3d25f213060f41b9854e8e2b512bbbd35ef3"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "f541324efcbad45f8d0bb0e727501579af003a9d9fced70059c3e54928d99c13"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.aarch64-linux-musl.tar.gz"
[[CFITSIO]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "27c1d06d335366b85b70dfbeac6be5c5f9368e6d"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "e931b084aabe40a472683dbd9b1da4e08fb921bc37c9bdcc2ae952cf579aa91c"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.armv7l-linux-gnueabihf.tar.gz"
[[CFITSIO]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "59d19f4000c7e0e7237eba7e28ae3c931d58643b"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "da3376c286711f82e4f759295a2a4eeec690bb9f6ed36bf87d78267e07621d3e"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.armv7l-linux-musleabihf.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "3d27a85394376f8ab12269fc0317d81c15233d34"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "c800f69a5e7156ea7c3180f94f1463b94c42d3f60f07951edf90a482b27769e5"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.i686-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "a07f0651caf1b39e869c4626b5fd8b83b6675820"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "85d68be7000a55bc91635bd5547c8c359aa61fe968db3f65cb73f8cccba282e2"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.i686-linux-musl.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "bcf3e66dc1386d8e2b35f6b081062fee265b1478"
os = "windows"

    [[CFITSIO.download]]
    sha256 = "be72064200d947cec1141d79003e5cbcb1411bf2cc2046818af70da0445bd3d3"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.i686-w64-mingw32.tar.gz"
[[CFITSIO]]
arch = "powerpc64le"
git-tree-sha1 = "cf4208343c5bf3d9c4cdd6a422ef5e6142038b6e"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "b541be27e19454f6553815602f1b122a9ce1db2c4d7310cad6ed32339458c93a"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.powerpc64le-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "13b61d4ee8903ae014086bb6c90bd4c7f0dac34c"
os = "macos"

    [[CFITSIO.download]]
    sha256 = "36036d72bbe616527fe61c6683b51e34652f4597f417318b5301217d161dfb09"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.x86_64-apple-darwin.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "aa5f51d5aa288c351344d577848b9ebe81fc2b65"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "4f672e776f4e0999ca92b3de08830dfb80959fec7a075f53c663685f4b94b843"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.x86_64-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "707a93fa3d990db496966538ed49e9ba8a464548"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "b7bcf5d6d3dd9c9b7c2ba3e7f34c7a09c8064a413da652a0ff5523d4bf9a0c80"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.x86_64-linux-musl.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "838749d47bc1277e92a1fdd35e6a74542be8b96f"
os = "freebsd"

    [[CFITSIO.download]]
    sha256 = "3269e9ab25ab7df71f9303346191b1886f69fa415dd59e99809eb4e20ca80d1f"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.x86_64-unknown-freebsd.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "63add26a3a6c4f4fed2a10aedb4345c816148a88"
os = "windows"

    [[CFITSIO.download]]
    sha256 = "71453e4ef3424d2ab3cd47d5f3ff836f09243ae54bef4bebec1e3c3163d7fe5d"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v3.49.0+0/CFITSIO.v3.49.0.x86_64-w64-mingw32.tar.gz"
