[[CFITSIO]]
arch = "aarch64"
git-tree-sha1 = "d564bcdee1c39d313a187d12ba396421fed11b2f"
os = "macos"

    [[CFITSIO.download]]
    sha256 = "c34c3f780fc01bf0e1a4150fa6cc566aa5be5452dadf33ffc310e6822e0682bd"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+0/CFITSIO.v4.3.1.aarch64-apple-darwin.tar.gz"
[[CFITSIO]]
arch = "aarch64"
git-tree-sha1 = "cc59d953fe899c8e1d7156f08ba8f59755aa0d56"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "bd314cefbef02e7de9827d608311e1105f92e2cba2b26c4136496e4ddcabe7d8"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+0/CFITSIO.v4.3.1.aarch64-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "aarch64"
git-tree-sha1 = "1b954f5e13f6b8d2b4d1e5a5becdaa80920211fb"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "0e330a755a3303c7df38d4394ad7329089dcb0249698dd9c45c9913c29306b47"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+0/CFITSIO.v4.3.1.aarch64-linux-musl.tar.gz"
[[CFITSIO]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e98ab37a477df0cc9c4b6a13d3364a3ed8ddf065"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "1d6118704af91d54733b8d81fe539a96fb0959501aae515689f04e6879c18d25"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+0/CFITSIO.v4.3.1.armv6l-linux-gnueabihf.tar.gz"
[[CFITSIO]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0591ccecf12a5a5bcca15d04636bc79f1072aa9f"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "071be9ab681997cc383255f61ec56a6382c2c967c73b295f10eb75de4ff00765"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+0/CFITSIO.v4.3.1.armv6l-linux-musleabihf.tar.gz"
[[CFITSIO]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2f37afcbbc5377978204a8a5ea3169ec061f7860"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "ee35674ffbe85a3ce8291132d42dc3b119e441042bfed8b32d89607c430b92a3"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+0/CFITSIO.v4.3.1.armv7l-linux-gnueabihf.tar.gz"
[[CFITSIO]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7a62792d9f74c258834a515c430c849287f6ba2a"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "3f9900a4e059ded727a5a67eee403d68cd199776608bed945dbb3547f453f829"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+0/CFITSIO.v4.3.1.armv7l-linux-musleabihf.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "c929890a1e859c5366347000bd163b18a339d6ea"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "515a2c23988ce4ab3274f6edd60221a60b34e0b4ee23bdc92498e473db3b813c"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+0/CFITSIO.v4.3.1.i686-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "b8620faff86a5e8a14f39258e2f17339b525ade1"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "6b8ab36416bdd956ba144438a9297e73bac228fd88d6354994edfd526f05c5f0"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+0/CFITSIO.v4.3.1.i686-linux-musl.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "54ba117576a45aef40b812093697fe3d5221ecc0"
os = "windows"

    [[CFITSIO.download]]
    sha256 = "426a8fabaa6bc78661c8d8d835186e4e4e02237b1555bf041d14645c9858e069"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+0/CFITSIO.v4.3.1.i686-w64-mingw32.tar.gz"
[[CFITSIO]]
arch = "powerpc64le"
git-tree-sha1 = "e02e4698b6016cbf43c33e1d3363123ba25afd7c"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "115fc4ccee5753f8192b6a3faaf7b6ebd51041d715021af266fd34ac12caa0d5"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+0/CFITSIO.v4.3.1.powerpc64le-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "5cf66549e2a4dad6e399c4e891b1a8cfc439391d"
os = "macos"

    [[CFITSIO.download]]
    sha256 = "d2d6b60df90410d3050130ae4a2cf1c0b286bfe3093283ff9e07358b12859526"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+0/CFITSIO.v4.3.1.x86_64-apple-darwin.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "ba9bfe2cce255c63bc76a856ba2ef2851593cafa"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "4ea5f03e1463c2d519a3d6528b1ecf509e673fa7ae104974038e7a89be840617"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+0/CFITSIO.v4.3.1.x86_64-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "3432a6904dbb7f8e120e7c543765baf2df1fe03e"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "76a652d9b797eb34b49b5a005493540d8014cfe74f0050bd145d2a9ae08b68ce"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+0/CFITSIO.v4.3.1.x86_64-linux-musl.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "282b950765ab396c6edd3e35ddc5f3c4b7f161ba"
os = "freebsd"

    [[CFITSIO.download]]
    sha256 = "17dec492f01c8d0e37917d5a5fbdd628ea10198f4c2d27b45df28eda34d3e1a3"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+0/CFITSIO.v4.3.1.x86_64-unknown-freebsd.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "1aa2f0480c8546dbd611578917656e26ca251393"
os = "windows"

    [[CFITSIO.download]]
    sha256 = "b011e593847441a6f52cab2ab8505f5cea9a12d9fff83ec4af969d2d4fcce0d0"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+0/CFITSIO.v4.3.1.x86_64-w64-mingw32.tar.gz"
