[[CFITSIO]]
arch = "aarch64"
git-tree-sha1 = "4134c35a2954124059d87b48ab449f9ee1165fa1"
os = "macos"

    [[CFITSIO.download]]
    sha256 = "00150fa7ea92568d89b24d976cc5a8b279a3a07a1fd7983b402c0e915d20e270"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+1/CFITSIO.v4.3.1.aarch64-apple-darwin.tar.gz"
[[CFITSIO]]
arch = "aarch64"
git-tree-sha1 = "52c6c945c6f0af0cf5b890cfc3e02a174f9f2417"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "76ad2e8295fb6f31789f310894c2b114a12c9971258c99b0a365ff71c4292d7e"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+1/CFITSIO.v4.3.1.aarch64-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "aarch64"
git-tree-sha1 = "3204745283ab5398bc25761ab8a75f272267585f"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "d79dea4d1e143c156ccd54631f3f41e96a3e08d510c244663652e639c60480ef"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+1/CFITSIO.v4.3.1.aarch64-linux-musl.tar.gz"
[[CFITSIO]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8bb65dcc504d77709ab49f67dbda58aaa3fcf5aa"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "4a5a064d3bb71171731c06206b3bb6f70b5d9dacb1302456131a8e4cc359f8e1"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+1/CFITSIO.v4.3.1.armv6l-linux-gnueabihf.tar.gz"
[[CFITSIO]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "29e41ecaf1ab632ccd4127d60a0176a6485888bc"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "9c80f3e1d092a2fefd586f5a724ce708b24cdbce7ae9d2c1b626fb8ee54d24d3"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+1/CFITSIO.v4.3.1.armv6l-linux-musleabihf.tar.gz"
[[CFITSIO]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "13ec92b9b86773e2dbe1f03fa6ae4cfedf290dc5"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "3aa783fbea790146019f3179f01d5352b95c3e43da4c0499006feeb5c168cb1f"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+1/CFITSIO.v4.3.1.armv7l-linux-gnueabihf.tar.gz"
[[CFITSIO]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "86a7ca291c3dc3ec084d8bc6948975b4a9329888"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "fd4a1272a7414123f471a67cc3498ff494a03a7864252ae923eebc993cc9f775"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+1/CFITSIO.v4.3.1.armv7l-linux-musleabihf.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "f8ade8454893b013fe6b31a06cca5ab0af04a651"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "301bc6d79d5ced89c88fafcab383d62bdefc279b81b31cb88ff5313cbdbe46c6"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+1/CFITSIO.v4.3.1.i686-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "80e21853afaa9f69546fdb3647fa9f1b97e05612"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "5b6738cb8c54d3196ba320d5a151b1e1b0b1847f81c804820f4929df8e0f36d4"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+1/CFITSIO.v4.3.1.i686-linux-musl.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "83877e53e55674d0c6d7d7f95a8471630c084c14"
os = "windows"

    [[CFITSIO.download]]
    sha256 = "d165f906390ffcbe5ff7e503b4905a3809d2947879161916c505a263f26d6198"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+1/CFITSIO.v4.3.1.i686-w64-mingw32.tar.gz"
[[CFITSIO]]
arch = "powerpc64le"
git-tree-sha1 = "f102ba33b87d661b1409e1e5af7c10837e007012"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "c399221cdf9913b664cf04f3834df8ae68ece8fee1b29087b5dbe3066089ad3f"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+1/CFITSIO.v4.3.1.powerpc64le-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "818de930d87b82684205ee1f964bf5917c3f7075"
os = "macos"

    [[CFITSIO.download]]
    sha256 = "6ae4b91b88860601537911d8cf365d5ac462a45142abd93b046dbb883b2eccef"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+1/CFITSIO.v4.3.1.x86_64-apple-darwin.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "fbe58325c59eeff25a5dd298572992c3b8846fa0"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "9d4a5f58f8c3237e44afcb7211a70f56d6cf2e972294b14f98cbcc473ca4fc66"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+1/CFITSIO.v4.3.1.x86_64-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "aa7005a501b7ae468c88ee6dfed25d65b77980fa"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "0d752e2b7cc8ef07f1662e3ec280256875403e51638cf0a4759029ede50dbf69"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+1/CFITSIO.v4.3.1.x86_64-linux-musl.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "9cff8aff4d991c0a56c525b9923a929596f7d95a"
os = "freebsd"

    [[CFITSIO.download]]
    sha256 = "c037e522db2e48b095221b8ea9ecfecca0e5eb7f06e1edb4eeadc0564015da36"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+1/CFITSIO.v4.3.1.x86_64-unknown-freebsd.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "ceac094b48bde61588edc79cae057cf08335a242"
os = "windows"

    [[CFITSIO.download]]
    sha256 = "10ce7cb382b4cb58779d25b8e22272503843f5cb475b8e0c9ac441edccf7dbf5"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.3.1+1/CFITSIO.v4.3.1.x86_64-w64-mingw32.tar.gz"
